version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerTp
      MYSQL_USER: user
      MYSQL_PASSWORD: supermp1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
